version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/var/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jenkins_network
networks:
  jenkins_network:
    external: true